version: '3'
services:
  front:
    build: .
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - .:/myapp
    networks:
      - external
networks:
  external:
    external: true
